apiVersion: v1
kind: Service
metadata:
  name: rm-demo-service
  labels:
    app: rm-demo-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: rm-demo-app
